import Head from 'next/head'
 import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from './banner'
import Homes from './home'
import {client} from './client'

export default function Home({bannerData,postData}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Homes mypost={postData.length && postData[0]}/>
      <Banner heroBanner={bannerData.length && bannerData[0]}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
export const getServerSideProps =async() => {
  
  const post = `*[_type == "post"]`;
  const postData =await client.fetch(post);

  const bannerQuery = `*[_type == "banner"]`;
  const bannerData =await client.fetch(bannerQuery);

  console.log(bannerData);
  return {
    props: {postData, bannerData }
  }
}